### ISSUE TITLE
No Gemfile

### ISSUE THREAD

**Issue by keithdadkins** [mitre/aws-s3-baseline#6]
Your usage says to run `bundle install` to install required gems, but there is no `Gemfile` present in the repo so the command fails.

**Comment by superyarick** [comment]
Until they fix the doc, add this - 

gem 'aws-sdk'
gem 'test-kitchen'
gem 'kitchen-terraform'
gem 'inspec'
gem 'kitchen-inspec'

The only require I see in the resources in aws-adk ...
